[package]
name = "rvepp_cli"
edition = "2021"
version.workspace = true

[dependencies]
rvepp_protection_layers = { path = "../rvepp_protection_layers" }
rvepp_configuration = { path = "../rvepp_configuration" }