[package]
name = "rvepp"
version = "2024.7.0"
edition = "2021"
publish = false

[workspace]
members = [
    "crates/rvepp_protection_layers"]

[workspace.package]
version = "2024.7.0"

[dependencies]
rvepp_protection_layers = { path = "crates/rvepp_protection_layers", platform = "linux" }
