[package]
name = "rvepp_configuration"
edition = "2021"

[dependencies]
rvepp_common = { path = "../rvepp_common" }
rvepp_cmdl_args = { path = "../rvepp_cmdl_args"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"